In [3]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [9]:
img = cv2.imread('picture/01_cat.jpg')

In [10]:
print(img)

[[[142 151 160]
  [146 155 164]
  [151 160 169]
  ...
  [156 172 185]
  [155 171 184]
  [154 170 183]]

 [[107 118 126]
  [112 123 131]
  [117 128 136]
  ...
  [155 171 184]
  [154 170 183]
  [153 169 182]]

 [[108 119 127]
  [112 123 131]
  [118 129 137]
  ...
  [154 170 183]
  [153 169 182]
  [152 168 181]]

 ...

 [[162 186 198]
  [157 181 193]
  [142 166 178]
  ...
  [181 204 206]
  [170 193 195]
  [149 172 174]]

 [[140 164 176]
  [147 171 183]
  [139 163 175]
  ...
  [167 187 188]
  [123 143 144]
  [104 124 125]]

 [[154 178 190]
  [154 178 190]
  [121 145 157]
  ...
  [185 198 200]
  [130 143 145]
  [129 142 144]]]


In [14]:
# 等待时间，毫秒级，0表示任意键终止，5000ms表示5s
cv2.imshow('image_cat',img)  
cv2.waitKey(0)  

# 销毁图像窗口
cv2.destroyAllWindows()

In [17]:
def cv_show(name,img):
    cv2.imshow(name,img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
cv_show('mao',img)

In [18]:
img.shape

(414, 500, 3)

In [25]:
new_img = img[0:500,0:300]# 读取部分
# cv_show('newmao',new_img)

In [ ]:
# 读取视频
