In [1]:
%matplotlib inline
import math
import time
import numpy as np
import torch
from d2l import torch as d2l

C:\env\python\lib\site-packages\torch\package\_directory_reader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy.core._multiarray_umath' (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}


In [2]:
def synthetic_data(w, b, num_examples): #@save
    """ ⽣成y=Xw+b+噪声"""
    X = torch.normal(0, 1, (num_examples, len(w)))
    y = torch.matmul(X, w) + b
    y += torch.normal(0, 0.01, y.shape)
    return X, y.reshape((-1, 1))


In [3]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = synthetic_data(true_w, true_b, 1000)


In [4]:
true_w,len(true_w)

(tensor([ 2.0000, -3.4000]), 2)

In [5]:
features

tensor([[-0.8810,  1.4664],
        [ 0.8509,  0.5062],
        [ 0.3601, -0.5477],
        ...,
        [-0.0266,  0.9273],
        [-0.0785, -0.2443],
        [-0.6892, -0.3903]])

In [6]:
labels[0],labels[1]

(tensor([-2.5582]), tensor([4.1656]))

In [7]:
features[:, 1]

tensor([ 1.4664e+00,  5.0619e-01, -5.4771e-01, -8.0915e-01,  7.1572e-02,
         1.3969e+00,  1.2961e-01, -1.9366e-01,  2.5513e-01, -2.0815e-01,
         1.6554e+00, -5.6408e-01, -3.6889e-02,  1.0399e+00, -4.2713e-01,
         1.6087e+00,  1.3363e+00, -7.5856e-01,  5.9623e-01, -9.9153e-01,
         7.1552e-01, -6.1242e-01,  2.6349e-01,  1.7198e+00, -3.0179e-01,
         1.0714e+00,  6.2668e-01, -3.4265e-01,  5.7097e-01, -7.2010e-01,
        -7.0215e-01,  7.5767e-01, -9.8255e-01,  7.6214e-01, -1.2266e+00,
        -5.0823e-01, -5.4932e-01, -7.3612e-01, -2.3769e-01, -1.2619e-01,
         8.3191e-01, -1.4218e+00,  1.3374e-01,  5.8419e-01,  1.3932e+00,
        -1.1884e+00,  8.1894e-01, -2.5805e-01, -1.2801e+00,  3.3041e-01,
         1.5229e-02, -3.2227e-01,  1.9069e+00,  3.7046e-01, -1.0738e+00,
         3.8884e-01, -1.7082e+00,  9.3824e-01, -1.5733e-01,  8.5241e-01,
        -6.4579e-01, -2.6506e-01,  1.7199e+00, -9.1342e-01, -2.7569e-01,
        -7.4853e-02,  9.3117e-01, -2.3419e+00,  2.7

In [14]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    # 这些样本是随机读取的，没有特定的顺序
    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        batch_indices = torch.tensor(indices[i: min(i + batch_size, num_examples)])
        yield features[batch_indices], labels[batch_indices]

In [17]:
batch_size = 10
for X, y in data_iter(batch_size, features, labels):
    print(X, '\n', y)
    break

NameError: name 'random' is not defined